#!/bin/sh

#	 _
#	| |__  ___ _ ____      ___ __ ___  _ __ ___
#	| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#	| |_) \__ \ |_) \ V  V /| | | | | | | | (__
#	|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#	          |_|

### Autostart
exec $HOME/.config/bspwm/autostart.sh &

# Settings
bspc monitor -d I II III IV V VI VII 
bspc config border_width		0
bspc config normal_border_color		"#d3869b"
bspc config focused_border_color 	"#7daea3"
bspc config single_monocle		false
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer 	true

###---Desktop Settings----###
bspc config top_padding 		36
bspc config bottom_padding 		2
bspc config left_padding 		10
bspc config right_padding 		10
bspc config window_gap 			8

# Rules
# bspc rule -a Brave-browser desktop='^2'
bspc rule -a Alacritty state=floating
bspc rule -a Spotify desktop='^5'
bspc rule -a Gimp state=floating 
