#!/bin/sh

#	 _
#	| |__  ___ _ ____      ___ __ ___  _ __ ___
#	| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#	| |_) \__ \ |_) \ V  V /| | | | | | | | (__
#	|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#	          |_|

#Killall Programs
killall -9 polybar sxhkd picom dunst

#Polybar
exec $HOME/.config/bspwm/scripts/launchBar.sh &

#Start Hotkey Deamon
sxhkd -c $HOME/.config/bspwm/sxhkdrc &

#Compositor
picom --config $HOME/.config/bspwm/picom.conf --experimental-backends &

#Set Wallpaper
exec $HOME/.config/bspwm/scripts/wallpaper.sh &

#Fix Cursor
xsetroot -cursor_name left_ptr &

#Notification
dunst -config $HOME/.config/bspwm/dunstrc &

# Settings
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 		0
bspc config normal_border_color		"#000000"
bspc config focused_border_color 	"#fbf1c7"
bspc config single_monocle 		false
bspc config borderless_monocle   	false
bspc config gapless_monocle      	false
bspc config focus_follows_pointer 	true

###---Desktop Settings----###
bspc config top_padding 		30
bspc config bottom_padding 		0
bspc config left_padding 		10
bspc config right_padding 		10
bspc config window_gap 			8
#bspc config pointer_action1 		move
#bspc config pointer_action2 		resize_side
#bspc config pointer_action3 		resize_corner
#bspc config click_to_focus 		none

# Rules
bspc rule -a alacritty desktop='^1'
bspc rule -a brave desktop='^2'
bspc rule -a Gimp state=floating 
bspc rule -a photoshop state=floating
